### ISSUE TITLE
这个Script有可能支持Radius认证么？

### ISSUE THREAD

**Issue by SharkIng** [frjalex/useful#3]
我尝试修改/etc/racoon/racoon.conf的配置让认证走radius，但是设置后racoon无法启动。

**Comment by SharkIng** [comment]
不对，是不修改也根本不能用。Racoon无法启动

**Comment by frjalex** [comment]
对不起，很久没维护repo了。。。
正在考虑把racoon换成strongswan以加入radius支持。
最近在用php写radius web management interface,打算把web前端写完了再更新脚本。


Alex R-J Fang
Email:frjalex@gmail.com

2015-05-07 17:33 GMT+08:00 David Jiang <notifications@github.com>:

**Comment by frjalex** [comment]
1.racoon默认没有radius support；需要安装libpam-radius-auth通过pam走radius认证，但很难维护且不支持计费；
2.能否提供racoon的log？这样方便我找到配置问题里面的错误

Alex R-J Fang
Email:frjalex@gmail.com

在 2015年5月7日 下午6:55，Alex Fang <frjalex@gmail.com>写道：
